chat:
  enabled: false
  message: "&cЧат на сервере отключён."

commands:
  block-all: false
  blacklist:
    - "msg"
    - "tell"
    - "w"
    - "r"
    - "me"
    - "say"
  message: "&cЭта команда заблокирована."

reload-message: "&aКонфигурация sChatManager перезагружена."
error-message: "&cОшибка в config.yml, настройки не изменены. Подробности в консоли."
